### ISSUE TITLE
标注不是针对起止位置，而是针对每一帧了

### ISSUE THREAD

**Issue by fahaihappy** [coin-dataset/annotation-tool#1]
感谢作者的分享，我在标注自己的视频时，选中起始位置后，标注标签时是对每一帧单独标注了，请问下这问题出在哪儿？
![image](https://user-images.githubusercontent.com/28214746/63686324-33894700-c834-11e9-9721-473eab7ea53e.png)

**Comment by FYtrace** [comment]
我也是这个问题~ 请问楼主咋解决的啊？
